### PR TITLE
Add oneof support

### PR DESCRIPTION
**Pull request by rayokota**
I've added simple oneof support for Protobuf.  Unfortunately it requires at least 2.6.0.

### CODE REVIEW

**Comment by os72** [comment]
Thank you. Could you also add a unit test for this?
Meanwhile I'll be pondering the compatibility question..

**Comment by os72** [comment]
@rayokota , BTW I'm refactoring this a bit, perhaps you could review?

**Comment by rayokota** [comment]
Thanks @os72 , a nice improvement.  I'll switch to the new API once you release :)

**Comment by os72** [comment]
Released version 1.0.0

**Comment by rayokota** [comment]
Great, thanks!

**Pull request merged**
